### ISSUE TITLE
I cannot compile the project

### ISSUE THREAD

**Issue by keymon** [Orange-OpenSource/sec-group-broker-filter#1]
Whenever I run `make` it says: `make: *** No targets specified and no makefile found. Stop.`

I also tried with:

```
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)
```

At least there is a 100% test coverage.

;)

Seriously, this looks a really nice and handy idea. Do you have a implementation to share? :)

**Comment by gberche-orange** [comment]
Hi @keymon 
We're just starting on this development (in java spring boot). This is only specs so far (that might still need refinements). We're happy to receive feedbacks though and potentially share implementation efforts.

**Comment by keymon** [comment]
That is great, thx. 

We will watch the project.
